FROM elasticsearch:8.12.1
ENV discovery.type=single-node
ENV xpack.security.enabled=false
ENV ELASTIC_PASSWORD=indiagolfninerniner 
ENV cluster.routing.allocation.disk.threshold_enabled=false
ENV logger.level=WARN