services:
  lobster-frontend:
    build: ./frontend
    ports:
      - "4173:4173"

  lobster-backend:
    build: ./backend
    depends_on:
      - lobster-postgres
    ports:
      - "3000:3000"
    networks:
      - lobster-backend-net

  lobster-postgres:
    build: ./sql
    volumes:
      - "pg-data:/var/lib/postgresql/data"
    networks:
      - lobster-backend-net

volumes:
  pg-data:
    driver: local

networks:
  lobster-backend-net: {}

# docker-compose up -d
# docker-compose down
