services:
  lobster-frontend:
    build: ./frontend
    ports:
      - "4173:4173"

  lobster-backend:
    build: ./backend
    volumes:
      - "lobster-img-data:/home/photos"
    depends_on:
      lobster-postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - lobster-backend-net

  lobster-postgres:
    build: ./sql
    volumes:
      - "lobster-pg-data:/var/lib/postgresql/data"
    networks:
      - lobster-backend-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U captain -d lobster"]
      interval: 10s
      timeout: 30s
      retries: 4

volumes:
  lobster-pg-data:
    driver: local
  lobster-img-data:
    driver: local

networks:
  lobster-backend-net: {}

# docker-compose build --no-cache
# docker-compose up -d
# docker-compose down
