INSERT INTO main.tool_categories (name, description, synonyms) VALUES
('cutting', '', '{}'),
('measuring', '', '{}'),
('gripping', '', '{clamping,fixtures}'),
('safety', '', '{}'),
('power tool', '', '{}'),
('hand tool', '', '{}'),
('wood-working', '', '{carpentry}'),
('metal-working', '', '{}'),
('glass-work', '', '{}'),
('earth-work', '', '{dirt,landscaping}'),
('leather-work', '', '{}'),
('fabrics', '', '{textiles,cloth,felt}'),
('stone-work', '', '{rock}'),
('ceramics', '', '{pottery}'),
('kitchen', '', '{cooking,baking}'),
('gardening', '', '{yard work,trees}'),
('weaving', '', '{knitting,embroidery,crochet,sewing}'),
('automotive', '', '{small engine}'),
('bicycling', '', '{}'),
('electronics', '', '{circuits}'),
('precision', '', '{}'),
('crafting', '', '{artistic}'),
('painting', '', '{}'),
('table top games', '', '{}'),
('writing', '', '{calligraphy}'),
('print-making', '', '{}'),
('sculpting', '', '{carving,molding}'),
('dyeing', '', '{}'),
('audio', '', '{}'),
('video', '', '{optical,photography,lighting}'),
('fitness', '', '{active,gym,weights,sports}'),
('hunting', '', '{fishing}'),
('books', '', '{guides,instructions}'),
('supports', '', '{scaffolding,work benches}'),
('tables', '', '{chairs,furniture}'),
('sharpening', '', '{honing}'),
('cleaning', '', '{}');
